function skillsMember() {
    var skills = [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Node",
        "Express",
        "MongoDB",
        "SQL",
        "Python",
        "Java",
        "C++",
        "C#",
        "Ruby",
        "PHP",
        "Swift",
        "Kotlin",
        "Objective-C",
        "Go",
        "Rust",
        "Scala",
        "Haskell",
        "TypeScript",
        "Dart",
        "R",
        "Perl",
        "Lua",
        "Shell",
        "PowerShell",
        "Bash",
        "SQL",
        "NoSQL",
        "Firebase",
        "AWS",
        "Azure",
        "Google Cloud",
        "Heroku",
        "Netlify",
        "Vercel",
        "Docker",
        "Kubernetes",
        "Jenkins",
        "Travis CI",
        "Circle CI",
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "Jira",
        "Confluence",
        "Trello",
        "Slack",
        "Zoom",
        "Microsoft Teams",
        "Discord",
        "Skype",
        "Google Meet",
        "WebEx",
        "Zoom",
        "Figma",
        "Sketch",
        "Adobe XD",
        "InVision",
        "Zeplin",
        "Marvel",
        "Photoshop",
        "Illustrator",
        "Premiere Pro",
        "After Effects",
        "Final Cut Pro",
        "Logic Pro",
        "Ableton Live",
        "Pro Tools",
        "FL Studio",
        "Cinema 4D",
        "Maya",
        "Blender",
        "Unity",
        "Unreal Engine",
        "ARKit",
        "ARCore",
        "Vuforia",
        "OpenCV",
        "TensorFlow",
        "Keras",
        "PyTorch",
        "Scikit-learn",
        "Pandas",
        "NumPy",
        "Matplotlib",
        "Seaborn",
        "Plotly",
        "Bokeh",
        "D3",
        "Tableau",
        "Power BI",
        "Looker",
        "Google Data Studio",
        "Data Studio",
        "Google Analytics",
        "Google Tag Manager",
        "Google Optimize"
    }